### ISSUE TITLE
[feature request] image display

### ISSUE THREAD

**Issue by w9DhSc** [neomacs-project/neomacs#53]
`Emacs` currently allows for image display within buffers via overlays, though this feature has several limitations (`Emacs`’s original design did not prioritize rich text and image integration).  I am curious whether there is interest in enhancing similar capabilities in `neomacs`, and how such features could be implemented given its design.

Personally I'd like to see images because it will enable inline previews for LaTeX/Typst, which is a part of my current everyday workflow in Emacs.  It could also improve functionalities in applications like `org-mode`, `logseq` and Jupyter notebooks (at the moment it's a mere dream, but they might be ported to `neomacs` if original `emacs` users start migrating).

**Comment by kchanqvq** [comment]
Hi @w9DhSc, thanks for you interest! 

In fact what you described is already doable and very easy to do in Neomacs, because Neomacs's buffer content is just arbitrary HTML DOM. You can just `(insert-nodes <pos> (make-element "img" …))`. If you happen to get Neomacs running, `M-x manual` and open the "Editing" section will give you some idea about the editing API. You can also take a look at `neomacs::dom` and existing modes implementations under `modes/`.

I'm closing the issue for now but feel free to continue the discussion here. Happy hacking!

**Comment by w9DhSc** [comment]
@kchanqvq thank you!  I tried
```lisp
(insert-nodes (focus)
              (make-element "img"
                            :src "neomacs://sys//home/path/to/image.jpg"))
```
and it indeed works.
